name: Michael Guo Blog
markdown: rdiscount
highlighter: pygents

permalink: /:year/:month/:day/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #
    
ga_id: #
ga_username: #
        
timezone: #
       